#ifndef SRC_ZCL_ZCL_SE_CUSTOM_ATTR_H_
#define SRC_ZCL_ZCL_SE_CUSTOM_ATTR_H_

#if ZCL_METERING_SUPPORT

#define ZCL_ATTRID_CUSTOM_HOT_WATER_PRESET  0xF000
#define ZCL_ATTRID_CUSTOM_COLD_WATER_PRESET 0xF001
#define ZCL_ATTRID_CUSTOM_WATER_STEP_PRESET 0xF002

#endif /* ZCL_METERING_SUPPORT */

#endif /* SRC_ZCL_ZCL_SE_CUSTOM_ATTR_H_ */
