#ifndef SRC_INCLUDE_ZCL_WATERMETERCFG_H_
#define SRC_INCLUDE_ZCL_WATERMETERCFG_H_

#define ZCL_CLUSTER_CUSTOM_WATERMETER       0xFC01

//Basic Information Attribute Set
#define ZCL_ATTRID_CUSTOM_HOT_WATER_PRESET  0x0000
#define ZCL_ATTRID_CUSTOM_COLD_WATER_PRESET 0x0001
#define ZCL_ATTRID_CUSTOM_HOT_WATER_STEP    0x0002
#define ZCL_ATTRID_CUSTOM_COLD_WATER_STEP   0x0003

#define ZCL_CMD_SET_CUSTOM_HOT_WATER_VALUE  0x00
#define ZCL_CMD_SET_CUSTOM_COLD_WATER_VALUE 0x01
#define ZCL_CMD_SET_CUSTOM_HOT_WATER_STEP   0x03
#define ZCL_CMD_SET_CUSTOM_COLD_WATER_STEP  0x04


#endif /* SRC_INCLUDE_ZCL_WATERMETERCFG_H_ */
